### ISSUE TITLE
Can't parse dates

### ISSUE THREAD

**Issue by jesjimher** [akashpjames/sms-import-for-ynab#1]
Hi, I've tried to create my first SMS template, but I've found a problem with dates. It seems that the app expects dates in a specific, complete format (day, month, year), but my SMS only shows day and month, not year. When I select the text that contains date at the template creation screen, and it makes me choose date format the only options are some kind of errors (NaN), and when an SMS is processed it shows an error that I think comes from YNAB API (error code 400), telling date format is incorrect (`date must be formatted as yyyy-mm-dd`).

A sample SMS is (relevant parts in bold):

`bankintercard informa **20/08** 22:29 Pago de **124,70EUR** con tu tarjeta acabada en 8356 en **BAR A****DA ESPOR** Mas info en 900811311 y www.bankintercard.com`

And my template is:

`bankintercard informa {{date}}{{variable0}} Pago de {{price}}EUR con tu tarjeta acabada en 8356 en {{memo}} Mas info en 900811311 y www.bankintercard.com`

Thanks!

**Comment by akashpjames** [comment]
Thanks for testing this app. I have fixed this earlier (when I was using this) but didn't commit to git. I have pushed a fix now and created a new release. You can fetch the latest from the release section.
(Currently 0.0.2 -> https://github.com/akashpjames/sms-import-for-ynab/releases/tag/0.0.2 )

While creating the template please choose auto-fetch when there is NaN in the date options(see the attached screenshot). It will use the date in which the SMS received to create the YNAB API.

It should work now. Please let me know. I will close this issue if it is working for you.

Unfortunately, you have to add a new token and begin from scratch. If time permits, I will try to create some option where the user can download the data and import it back whenever the user has to reinstall the app.
<img width="434" alt="auto fetch option" src="https://user-images.githubusercontent.com/9964394/63436212-eb3de380-c445-11e9-809c-f76e9646f10b.png">

**Comment by jesjimher** [comment]
It works! Thanks!
